//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommentsTrial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParentComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblParentComment()
        {
            this.tblChildComments = new HashSet<tblChildComment>();
        }
    
        public int CommentID { get; set; }
        public string Username { get; set; }
        public string CommentMessage { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<int> PostID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChildComment> tblChildComments { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblPost tblPost { get; set; }
    }
}
